# Generated by Django 5.0.2 on 2024-03-04 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pixel_C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(null=True)),
                ('Y', models.IntegerField(null=True)),
                ('z1', models.IntegerField()),
                ('z2', models.IntegerField()),
                ('z3', models.IntegerField()),
                ('lable1', models.CharField(max_length=255)),
                ('lable2', models.CharField(max_length=255)),
                ('lable3', models.CharField(max_length=255)),
                ('update_time1', models.DateTimeField(auto_now=True)),
                ('update_time2', models.DateTimeField(auto_now=True)),
                ('update_time3', models.DateTimeField(auto_now=True)),
                ('del_time1', models.IntegerField(default=300)),
                ('del_time2', models.IntegerField(default=300)),
                ('del_time3', models.IntegerField(default=300)),
            ],
        ),
        migrations.CreateModel(
            name='lable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lable_text', models.CharField(max_length=255)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('del_time', models.IntegerField()),
                ('lable_url', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pixel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixel.pixel_c')),
            ],
        ),
    ]
