# Generated by Django 5.0.2 on 2024-03-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pixel_c',
            old_name='Y',
            new_name='y',
        ),
    ]
