# Generated by Django 5.0.2 on 2024-03-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0002_rename_y_pixel_c_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixel_c',
            name='x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pixel_c',
            name='y',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pixel_c',
            name='z1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pixel_c',
            name='z2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pixel_c',
            name='z3',
            field=models.IntegerField(null=True),
        ),
    ]
