# Generated by Django 5.0.2 on 2024-03-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0003_alter_pixel_c_x_alter_pixel_c_y_alter_pixel_c_z1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixel_c',
            name='z',
            field=models.CharField(default='#FFFFFFFF', max_length=12),
        ),
        migrations.AlterField(
            model_name='pixel_c',
            name='z1',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pixel_c',
            name='z2',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pixel_c',
            name='z3',
            field=models.IntegerField(max_length=12, null=True),
        ),
    ]
