# Generated by Django 5.0.2 on 2024-03-12 03:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0004_pixel_c_z_alter_pixel_c_z1_alter_pixel_c_z2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixel_c',
            name='del_time1',
            field=models.BigIntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='pixel_c',
            name='del_time2',
            field=models.BigIntegerField(default=301),
        ),
        migrations.AlterField(
            model_name='pixel_c',
            name='del_time3',
            field=models.BigIntegerField(default=302),
        ),
        migrations.AlterField(
            model_name='pixel_c',
            name='update_time1',
            field=models.BigIntegerField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pixel_c',
            name='update_time2',
            field=models.BigIntegerField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pixel_c',
            name='update_time3',
            field=models.BigIntegerField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pixel_c',
            name='z1',
            field=models.CharField(default='#FFFFFFFF', max_length=12),
        ),
        migrations.AlterField(
            model_name='pixel_c',
            name='z2',
            field=models.CharField(default='#FFFFFFFF', max_length=12),
        ),
        migrations.AlterField(
            model_name='pixel_c',
            name='z3',
            field=models.CharField(default='#FFFFFFFF', max_length=12),
        ),
    ]
