# Generated by Django 5.0.2 on 2024-03-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0005_alter_pixel_c_del_time1_alter_pixel_c_del_time2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixel_c',
            name='del_time2',
            field=models.BigIntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='pixel_c',
            name='del_time3',
            field=models.BigIntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='pixel_c',
            name='z1',
            field=models.BigIntegerField(default='4294967295'),
        ),
        migrations.AlterField(
            model_name='pixel_c',
            name='z2',
            field=models.BigIntegerField(default='4294967295'),
        ),
        migrations.AlterField(
            model_name='pixel_c',
            name='z3',
            field=models.BigIntegerField(default='4294967295'),
        ),
    ]
