# Generated by Django 5.0.2 on 2024-03-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0008_remove_pixel_c_z_alter_pixel_c_lable1_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='pixel_c',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pixel_c',
            name='update_time1',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pixel_c',
            name='update_time2',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pixel_c',
            name='update_time3',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
