# Generated by Django 5.0.2 on 2024-04-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0015_pixel_a_pixel_b_remove_pixel_c_z_lable_index_abc_and_more'),
    ]

