# Generated by Django 4.1 on 2024-10-30 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pixel', '0016_pixel_a_pixel_b_remove_pixel_c_z_pixel_c_u1_and_more'),
    ]

    operations = [


        migrations.AddField(
            model_name='lable',
            name='add_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lable_add_user', to=settings.AUTH_USER_MODEL),
        ),

        migrations.AlterField(
            model_name='lable',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lable_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
